// --- DATA REPOSITORY (UPGRADED) --- //
window.AppData = {
    topNav: [
        { id: 'study', icon: 'book-open', label: 'Study' },
        { id: 'utilities', icon: 'tools', label: 'Utilities' },
        { id: 'sound', icon: 'music', label: 'Sound' },
        { id: 'other', icon: 'sliders-h', label: 'Other' }
    ],
    // --- MATHEMATICS ---
    formulas: [
        {t:"Quadratic Equ", d:"x = (-b ± √(b² - 4ac)) / 2a"},
        {t:"Pythagorean Thm", d:"a² + b² = c²"},
        {t:"Distance", d:"d = √((x₂-x₁)² + (y₂-y₁)²)"},
        {t:"Midpoint", d:"M = ((x₁+x₂)/2, (y₁+y₂)/2)"},
        {t:"Slope", d:"m = (y₂ - y₁) / (x₂ - x₁)"},
        {t:"Circle Area", d:"A = πr²"},
        {t:"Circle Circumf.", d:"C = 2πr"},
        {t:"Sphere Vol", d:"V = (4/3)πr³"},
        {t:"Cylinder Vol", d:"V = πr²h"},
        {t:"Cone Vol", d:"V = (1/3)πr²h"},
        {t:"Trapezoid Area", d:"A = ((a+b)/2)h"},
        {t:"Log Product", d:"log(xy) = log(x) + log(y)"},
        {t:"Log Quotient", d:"log(x/y) = log(x) - log(y)"},
        {t:"Log Power", d:"log(x^n) = n·log(x)"},
        {t:"Euler's Id.", d:"e^(iπ) + 1 = 0"},
        {t:"SOH CAH TOA", d:"sin=O/H, cos=A/H, tan=O/A"},
        {t:"Law of Sines", d:"a/sinA = b/sinB = c/sinC"},
        {t:"Law of Cosines", d:"c² = a² + b² - 2ab cosC"},
        {t:"Trig Identity", d:"sin²θ + cos²θ = 1"},
        {t:"Double Angle", d:"sin(2θ) = 2sinθcosθ"},
        {t:"Derivative Power", d:"d/dx(x^n) = nx^(n-1)"},
        {t:"Product Rule", d:"(uv)' = u'v + uv'"},
        {t:"Quotient Rule", d:"(u/v)' = (u'v - uv')/v²"},
        {t:"Chain Rule", d:"d/dx f(g(x)) = f'(g(x))g'(x)"},
        {t:"Integral Power", d:"∫ x^n dx = x^(n+1)/(n+1) + C"},
        {t:"Kinematics 1", d:"v = u + at"},
        {t:"Kinematics 2", d:"s = ut + ½at²"},
        {t:"Kinematics 3", d:"v² = u² + 2as"},
        {t:"Force", d:"F = ma"},
        {t:"Kinetic Energy", d:"KE = ½mv²"},
        {t:"Potential Energy", d:"PE = mgh"},
        {t:"Work", d:"W = Fd cosθ"},
        {t:"Power", d:"P = W/t"},
        {t:"Momentum", d:"p = mv"},
        {t:"Ohm's Law", d:"V = IR"},
        {t:"Ideal Gas", d:"PV = nRT"},
        {t:"Density", d:"ρ = m/v"},
        {t:"Molarity", d:"M = mol / L"},
        {t:"pH", d:"pH = -log[H+]"},
        {t:"Entropy", d:"S = k ln Ω"},
        {t:"Sum/Diff Sin", d:"sin(A±B) = sinAcosB ± cosAsinB"},
        {t:"Sum/Diff Cos", d:"cos(A±B) = cosAcosB ∓ sinAsinB"},
        {t:"Limit def.", d:"lim(x->c) f(x) = L"},
        {t:"Deriv. e^x", d:"d/dx(e^x) = e^x"},
        {t:"Deriv. ln(x)", d:"d/dx(ln x) = 1/x"},
        {t:"Integral 1/x", d:"∫(1/x)dx = ln|x| + C"},
        {t:"Statistics Mean", d:"μ = (Σx) / N"},
        {t:"Variance", d:"σ² = Σ(x - μ)² / N"},
        {t:"Std Deviation", d:"σ = √variance"},
        {t:"Gravitation", d:"F = G(m₁m₂)/r²"},
        {t:"Coulomb's Law", d:"F = k(q₁q₂)/r²"},
        {t:"Relativity", d:"E = mc²"},
        {t:"Binomial Theorem", d:"(a+b)^n = Σ C(n,k) a^(n-k) b^k"},
        {t:"Taylor Series", d:"f(x) = Σ f^(n)(a)/n! (x-a)^n"},
        {t:"Fourier Transform", d:"F(ω) = ∫ f(t) e^(-iωt) dt"},
        {t:"Laplace Transform", d:"F(s) = ∫ f(t) e^(-st) dt"},
        {t:"Matrix Determinant", d:"det(A) = Σ (-1)^i+j M_ij"},
        {t:"Eigenvalues", d:"det(A - λI) = 0"},
        {t:"Cross Product", d:"a×b = |i    j    k; ax ay az; bx by bz|"},
        {t:"Dot Product", d:"a·b = ax·bx + ay·by + az·bz"},
        {t:"Vector Magnitude", d:"|v| = √(x² + y² + z²)"},
        {t:"Complex Numbers", d:"z = a + bi, |z| = √(a² + b²)"},
        {t:"De Moivre's Theorem", d:"(cosθ + i sinθ)^n = cos(nθ) + i sin(nθ)"},
        {t:"Polar Form", d:"z = r(cosθ + i sinθ)"},
        {t:"Hyperbolic Sin", d:"sinh(x) = (e^x - e^(-x))/2"},
        {t:"Hyperbolic Cos", d:"cosh(x) = (e^x + e^(-x))/2"},
        {t:"Gamma Function", d:"Γ(z) = ∫ t^(z-1) e^(-t) dt"},
        {t:"Beta Function", d:"B(m,n) = ∫ x^(m-1) (1-x)^(n-1) dx"},
        {t:"Stirling's Approx", d:"n! ≈ √(2πn) (n/e)^n"},
        {t:"Prime Number Theorem", d:"π(x) ~ x/ln(x)"},
        {t:"Riemann Hypothesis", d:"Non-trivial zeros of ζ(s) have Re(s)=1/2"},
        {t:"Normal Distribution", d:"f(x) = (1/σ√(2π)) e^(-(x-μ)²/(2σ²))"},
        {t:"Poisson Distribution", d:"P(X=k) = e^(-λ) λ^k / k!"},
        {t:"Chi-Squared Test", d:"χ² = Σ (O_i - E_i)² / E_i"},
        {t:"Correlation", d:"r = Σ((x-μx)(y-μy)) / (σx σy)"},
        {t:"Regression Line", d:"y = mx + b, m = r(σy/σx), b = μy - mμx"},
        {t:"Bayes' Theorem", d:"P(A|B) = P(B|A) P(A) / P(B)"},
        {t:"Central Limit Theorem", d:"Sample means → Normal as n→∞"},
        {t:"Confidence Interval", d:"μ ± z*(σ/√n) for 95% CI"},
        {t:"Hypothesis Testing", d:"H₀: null, H₁: alternative, p-value < α"},
        {t:"ANOVA", d:"F = (SSB/dfB) / (SSW/dfW)"},
        {t:"Permutations", d:"P(n,r) = n! / (n-r)!"},
        {t:"Combinations", d:"C(n,r) = n! / (r!(n-r)!)"},
        {t:"Probability Rules", d:"P(A∪B) = P(A)+P(B)-P(A∩B)"},
        {t:"Expected Value", d:"E[X] = Σ x P(X=x)"},
        {t:"Variance Formula", d:"Var(X) = E[X²] - (E[X])²"},
        {t:"Geometric Series", d:"Σ ar^(n-1) = a(1-r^n)/(1-r)"},
        {t:"Arithmetic Series", d:"Σ (a + (n-1)d) = n/2 (2a + (n-1)d)"},
        {t:"Compound Interest", d:"A = P(1 + r/n)^(nt)"},
        {t:"Present Value", d:"PV = FV / (1 + r)^t"},
        {t:"Amortization", d:"PMT = P[r(1+r)^n]/[(1+r)^n - 1]"},
        {t:"Black-Scholes", d:"C = S N(d1) - K e^(-rT) N(d2)"},
        {t:"CAPM", d:"E[R_i] = R_f + β(R_m - R_f)"},
        {t:"Sharpe Ratio", d:"(R_p - R_f) / σ_p"},
        {t:"Portfolio Variance", d:"σ²_p = Σ Σ w_i w_j Cov(i,j)"},
        {t:"Markowitz Model", d:"Min σ²_p s.t. E[R_p] ≥ target"},
        {t:"Game Theory", d:"Nash Equilibrium: No player can benefit by changing strategy"},
        {t:"Linear Programming", d:"Max/Min c·x s.t. A·x ≤ b, x ≥ 0"},
        {t:"Simplex Method", d:"Algorithm for solving linear programming problems"},
        {t:"Dijkstra's Algorithm", d:"Shortest path in weighted graph"},
        {t:"Bellman-Ford", d:"Shortest path with negative weights"},
        {t:"Floyd-Warshall", d:"All-pairs shortest paths"},
        {t:"Kruskal's Algorithm", d:"Minimum spanning tree"},
        {t:"Prim's Algorithm", d:"Minimum spanning tree"},
        {t:"Topological Sort", d:"Linear ordering of vertices in DAG"},
        {t:"Dynamic Programming", d:"Solve complex problems by breaking into subproblems"},
        {t:"Greedy Algorithm", d:"Make locally optimal choice at each step"},
        {t:"Divide & Conquer", d:"Break problem into subproblems, solve recursively"},
        {t:"Backtracking", d:"Try all possibilities, backtrack on failure"},
        {t:"Branch & Bound", d:"Enumerate solutions with bounds"},
        {t:"FFT", d:"Fast Fourier Transform O(n log n)"},
        {t:"RSA Encryption", d:"Public-key cryptosystem using prime factors"},
        {t:"Diffie-Hellman", d:"Key exchange protocol"},
        {t:"SHA-256", d:"Cryptographic hash function"},
        {t:"Merkle Tree", d:"Hash tree for efficient verification"},
        {t:"Consensus Algorithms", d:"Byzantine Fault Tolerance, Proof of Work/Stake"}
    ],
    // --- SCIENCE ---
    science: [
        {t:"Mitosis", d:"Cell division -> 2 identical diploid cells (growth/repair)."}, 
        {t:"Meiosis", d:"Cell division -> 4 unique haploid gametes (reproduction)."},
        {t:"DNA", d:"Deoxyribonucleic Acid. Double helix. Stores genetic code (A-T, C-G)."},
        {t:"RNA", d:"Ribonucleic Acid. Single strand. Messenger involved in protein synthesis (A-U, C-G)."},
        {t:"Central Dogma", d:"DNA -> transcription -> RNA -> translation -> Protein."},
        {t:"Photosynthesis", d:"6CO2 + 6H2O + Light -> C6H12O6 (Glucose) + 6O2 (Chloroplasts)."},
        {t:"Cellular Resp.", d:"C6H12O6 + 6O2 -> 6CO2 + 6H2O + ATP (Mitochondria)."},
        {t:"ATP", d:"Adenosine Triphosphate. Energy currency of the cell."},
        {t:"Enzymes", d:"Biological catalysts that speed up reactions by lowering activation energy."},
        {t:"Osmosis", d:"Diffusion of water across a semi-permeable membrane (Low -> High solute)."},
        {t:"Homeostasis", d:"Maintaining a stable internal environment despite external changes."},
        {t:"Natural Selection", d:"Survival of the fittest. Mechanism of evolution (Darwin)."},
        {t:"Atom", d:"Basic unit of matter. Protons (+), Neutrons (0), Electrons (-)."},
        {t:"Isotope", d:"Same element (protons), different mass (neutrons)."},
        {t:"Ion", d:"Charged atom. Cation (+) lost e-, Anion (-) gained e-."},
        {t:"Ionic Bond", d:"Transfer of electrons between metal and non-metal."},
        {t:"Covalent Bond", d:"Sharing of electrons between non-metals."},
        {t:"pH Scale", d:"0-6 Acidic (H+), 7 Neutral, 8-14 Basic (OH-)."},
        {t:"Newton 1st Law", d:"Inertia: Object stays at rest/motion unless acted on."}, 
        {t:"Newton 2nd Law", d:"F = ma. Force equals mass times acceleration."}, 
        {t:"Newton 3rd Law", d:"Action = Reaction. Equal and opposite forces."},
        {t:"Thermodynamics 1", d:"Energy cannot be created or destroyed (Conservation)."},
        {t:"Thermodynamics 2", d:"Entropy (disorder) of an isolated system always increases."},
        {t:"Doppler Effect", d:"Change in frequency of a wave due to motion of source/observer."},
        {t:"Refraction", d:"Bending of light as it passes through different mediums (Snell's Law)."},
        {t:"Plate Tectonics", d:"Movement of Earth's lithospheric plates causing quakes/volcanoes."},
        {t:"Big Bang", d:"Universe began as a singularity approx 13.8 billion years ago."},
        {t:"Mendelian Genetics", d:"Dominant/Recessive traits. Punnett squares. Law of segregation/independent assortment."},
        {t:"Genetic Code", d:"64 codons -> 20 amino acids. Universal across life."},
        {t:"PCR", d:"Polymerase Chain Reaction. Amplifies DNA segments."},
        {t:"Gel Electrophoresis", d:"Separates DNA fragments by size using electric field."},
        {t:"CRISPR", d:"Gene editing technology. Cuts DNA at specific sequences."},
        {t:"Endocrine System", d:"Hormones regulate body functions (Insulin, Testosterone, Estrogen)."},
        {t:"Nervous System", d:"Neurons transmit electrical signals. CNS (Brain/Spinal) + PNS."},
        {t:"Immune System", d:"Innate/Adaptive immunity. Antibodies, T-cells, B-cells."},
        {t:"Cardiovascular", d:"Heart pumps blood. Arteries (oxygenated), Veins (deoxygenated)."},
        {t:"Respiratory", d:"Lungs exchange O2/CO2. Alveoli for gas exchange."},
        {t:"Digestive", d:"Break down food. Enzymes in mouth, stomach, intestines."},
        {t:"Excretory", d:"Kidneys filter waste. Nephrons remove urea, maintain pH."},
        {t:"Skeletal System", d:"Bones provide structure. Calcium, Phosphorus. Marrow produces blood cells."},
        {t:"Muscular System", d:"Voluntary/Involuntary muscles. Actin/Myosin filaments."},
        {t:"Ecosystem", d:"Community + Environment. Producers, Consumers, Decomposers."},
        {t:"Food Chain", d:"Energy flow: Sun -> Plants -> Herbivores -> Carnivores."},
        {t:"Carbon Cycle", d:"CO2 fixation in photosynthesis, release in respiration/decomposition."},
        {t:"Nitrogen Cycle", d:"N2 -> Ammonia -> Nitrates -> Plants -> Animals -> Decomposition."},
        {t:"Water Cycle", d:"Evaporation -> Condensation -> Precipitation -> Runoff."},
        {t:"Biodiversity", d:"Variety of life. Genetic, Species, Ecosystem diversity."},
        {t:"Endangered Species", d:"Threatened with extinction. IUCN Red List categories."},
        {t:"Climate Change", d:"Global warming from greenhouse gases (CO2, CH4, N2O)."},
        {t:"Acid Rain", d:"SO2 + NOx + H2O -> H2SO4/HNO3. Damages ecosystems."},
        {t:"Ozone Depletion", d:"CFCs destroy stratospheric ozone layer."},
        {t:"Greenhouse Effect", d:"Atmospheric gases trap heat. Natural warming enhanced by humans."},
        {t:"Periodic Table", d:"Elements arranged by atomic number. Groups/Families have similar properties."},
        {t:"Valence Electrons", d:"Electrons in outermost shell. Determine reactivity."},
        {t:"Electronegativity", d:"Atom's ability to attract electrons in bond (F highest)."},
        {t:"Lewis Structures", d:"Electron dot diagrams showing bonding pairs/lone pairs."},
        {t:"VSEPR Theory", d:"Molecular geometry based on electron repulsion."},
        {t:"Hybridization", d:"Mixing of atomic orbitals (sp, sp2, sp3)."},
        {t:"Molecular Orbital", d:"Molecular orbitals from atomic orbital combination."},
        {t:"Stoichiometry", d:"Quantitative relationships in chemical reactions."},
        {t:"Limiting Reactant", d:"Reactant that determines maximum product yield."},
        {t:"Percent Yield", d:"Actual yield / Theoretical yield × 100%"},
        {t:"Reaction Rates", d:"Speed of chemical reactions. Affected by concentration, temperature, catalysts."},
        {t:"Activation Energy", d:"Minimum energy required for reaction to occur."},
        {t:"Catalysts", d:"Speed up reactions without being consumed."},
        {t:"Equilibrium", d:"Forward = Reverse rates. K_eq = [products]/[reactants]"},
        {t:"Le Chatelier", d:"System shifts to relieve stress (concentration, temperature, pressure)."},
        {t:"Acids/Bases", d:"Arrhenius: H+/OH-. Brønsted-Lowry: Proton donor/acceptor."},
        {t:"pKa", d:"-log(Ka). Measure of acid strength (lower = stronger acid)."},
        {t:"Buffers", d:"Resist pH changes. Weak acid + conjugate base."},
        {t:"Titration", d:"Determine concentration by gradual addition of reagent."},
        {t:"Redox Reactions", d:"Electron transfer. Oxidation (lose e-), Reduction (gain e-)."},
        {t:"Electrolysis", d:"Using electricity to drive non-spontaneous reactions."},
        {t:"Galvanic Cells", d:"Spontaneous redox reactions produce electricity."},
        {t:"Nuclear Fission", d:"Heavy nucleus splits into lighter nuclei + energy."},
        {t:"Nuclear Fusion", d:"Light nuclei combine into heavier nuclei + energy."},
        {t:"Half-Life", d:"Time for half of radioactive sample to decay."},
        {t:"Radioactive Decay", d:"Unstable nucleus emits radiation (α, β, γ)."},
        {t:"Quantum Mechanics", d:"Wave-particle duality. Uncertainty principle. Quantum numbers."},
        {t:"Photoelectric Effect", d:"Light can eject electrons from metal surface."},
        {t:"Wave-Particle Duality", d:"Matter and energy exhibit both wave and particle properties."},
        {t:"Heisenberg Uncertainty", d:"Cannot know both position and momentum precisely."},
        {t:"Schrödinger Equation", d:"Fundamental equation of quantum mechanics."},
        {t:"Quantum Numbers", d:"n (energy), l (shape), m_l (orientation), m_s (spin)."},
        {t:"Electron Configuration", d:"Arrangement of electrons in atomic orbitals."},
        {t:"Aufbau Principle", d:"Electrons fill lowest energy orbitals first."},
        {t:"Pauli Exclusion", d:"Maximum 2 electrons per orbital, opposite spins."},
        {t:"Hund's Rule", d:"Electrons occupy orbitals singly before pairing."},
        {t:"Electromagnetic Spectrum", d:"Radio → Microwave → IR → Visible → UV → X-ray → Gamma."},
        {t:"Blackbody Radiation", d:"Object emits radiation based on temperature."},
        {t:"Special Relativity", d:"Speed of light constant. Time dilation, length contraction."},
        {t:"General Relativity", d:"Gravity as curvature of spacetime."},
        {t:"Cosmology", d:"Study of universe origin, evolution, fate."},
        {t:"Dark Matter", d:"Invisible matter detected by gravitational effects."},
        {t:"Dark Energy", d:"Causes accelerated expansion of universe."},
        {t:"String Theory", d:"Fundamental particles as vibrating strings."},
        {t:"Quantum Gravity", d:"Unification of quantum mechanics and general relativity."},
        {t:"Higgs Boson", d:"Particle that gives other particles mass."},
        {t:"Standard Model", d:"Theory describing fundamental particles and forces."},
        {t:"Grand Unified Theory", d:"Unifies electromagnetic, weak, strong forces."},
        {t:"Theory of Everything", d:"Unifies all fundamental forces including gravity."}
    ],
    // --- LANGUAGE ARTS ---
    ela: [
        {t:"Metaphor", d:"Direct comparison asserting one thing IS another (e.g., 'Time is a thief')."}, 
        {t:"Simile", d:"Comparison using 'like' or 'as' (e.g., 'Strong as an ox')."},
        {t:"Personification", d:"Attributing human traits to non-human objects/animals."}, 
        {t:"Hyperbole", d:"Extreme exaggeration for emphasis (e.g., 'I could eat a horse')."},
        {t:"Alliteration", d:"Repetition of initial consonant sounds (e.g., 'Peter Piper picked')."}, 
        {t:"Onomatopoeia", d:"Words that imitate natural sounds (e.g., 'Snap', 'Crackle', 'Pop')."},
        {t:"Oxymoron", d:"Combining contradictory terms (e.g., 'Deafening silence', 'Wise fool')."}, 
        {t:"Irony (Verbal)", d:"Saying the opposite of what is meant (Sarcasm)."},
        {t:"Irony (Situational)", d:"Outcome is contrary to what was expected."},
        {t:"Irony (Dramatic)", d:"Audience knows something the characters do not."},
        {t:"Symbolism", d:"Use of symbols to represent ideas or qualities (e.g., Dove = Peace)."},
        {t:"Allegory", d:"Narrative with a hidden moral or political meaning (e.g., 'Animal Farm')."},
        {t:"Juxtaposition", d:"Placing two things close together for contrasting effect."},
        {t:"Ethos", d:"Rhetorical appeal to credibility or character."},
        {t:"Pathos", d:"Rhetorical appeal to emotion."},
        {t:"Logos", d:"Rhetorical appeal to logic and reason."},
        {t:"Ad Hominem", d:"Fallacy: Attacking the person rather than the argument."},
        {t:"Strawman", d:"Fallacy: Misrepresenting an argument to make it easier to attack."},
        {t:"Slippery Slope", d:"Fallacy: Asserting one event will inevitable lead to a catastrophic chain."},
        {t:"Noun", d:"Person, place, thing, or idea."},
        {t:"Verb", d:"Action or state of being."},
        {t:"Adjective", d:"Describes or modifies a noun (e.g., 'red house', 'quickly')."},
        {t:"Adverb", d:"Describes or modifies a verb, adjective, or other adverb."},
        {t:"Pronoun", d:"Replaces a noun (he, she, it, they, we, I, you)."},
        {t:"Preposition", d:"Shows relationship between nouns (in, on, at, by, for, with)."},
        {t:"Conjunction", d:"Connects clauses or sentences (and, but, or, so, because)."},
        {t:"Interjection", d:"Expresses emotion (wow, oh, hey, ouch)."},
        {t:"Subject", d:"Who/what the sentence is about."},
        {t:"Predicate", d:"What the subject does or is."},
        {t:"Clause", d:"Group of words with subject and verb. Independent/Dependent."},
        {t:"Phrase", d:"Group of words without subject-verb. Prepositional, gerund, etc."},
        {t:"Active Voice", d:"Subject performs the action (e.g., 'Dog bit man')."},
        {t:"Passive Voice", d:"Subject receives the action (e.g., 'Man was bitten by dog')."},
        {t:"Mood", d:"Indicative (statement), Imperative (command), Subjunctive (hypothetical)."},
        {t:"Tense", d:"Present, Past, Future. Simple, Continuous, Perfect, Perfect Continuous."},
        {t:"Aspect", d:"Simple, Progressive, Perfect, Perfect Progressive."},
        {t:"Gerund", d:"Verb form ending in -ing used as a noun (e.g., 'Swimming is fun')."},
        {t:"Participle", d:"Verb form used as adjective (Present: -ing, Past: -ed/-en)."},
        {t:"Infinitive", d:"Base verb form with 'to' (e.g., 'to run', 'to be')."},
        {t:"Appositive", d:"Noun phrase that renames another noun (e.g., 'My dog, Spot, is friendly')."},
        {t:"Parallel Structure", d:"Similar grammatical form for similar ideas."},
        {t:"Thesis Statement", d:"Main argument or claim of an essay."},
        {t:"Topic Sentence", d:"Main idea of a paragraph."},
        {t:"Hook", d:"Opening that grabs reader's attention."},
        {t:"Transition", d:"Words/phrases that connect ideas (however, therefore, in addition)."},
        {t:"Concession", d:"Acknowledging opposing viewpoint before countering."},
        {t:"Counterargument", d:"Addressing and refuting opposing claims."},
        {t:"Evidence", d:"Facts, quotes, examples supporting claims."},
        {t:"Analysis", d:"Explanation of how evidence supports thesis."},
        {t:"Rhetorical Question", d:"Question asked for effect, not requiring answer."},
        {t:"Allusion", d:"Reference to another work, person, or event."},
        {t:"Foreshadowing", d:"Hint of what will happen later."},
        {t:"Flashback", d:"Interruption showing past events."},
        {t:"Motif", d:"Recurring element that develops theme."},
        {t:"Theme", d:"Central message or insight about life."},
        {t:"Tone", d:"Author's attitude toward subject."},
        {t:"Mood", d:"Emotional atmosphere created for reader."},
        {t:"Point of View", d:"Perspective from which story is told (1st, 2nd, 3rd person)."},
        {t:"Protagonist", d:"Main character, hero of the story."},
        {t:"Antagonist", d:"Character opposing the protagonist."},
        {t:"Dynamic Character", d:"Character who changes significantly."},
        {t:"Static Character", d:"Character who remains unchanged."},
        {t:"Round Character", d:"Complex character with many traits."},
        {t:"Flat Character", d:"Simple character with few traits."},
        {t:"Archetype", d:"Universal character pattern (hero, mentor, trickster)."},
        {t:"Conflict", d:"Struggle between opposing forces (man vs man, man vs nature, etc.)."},
        {t:"Climax", d:"Most intense moment of conflict."},
        {t:"Resolution", d:"How conflict is resolved."},
        {t:"Denouement", d:"Final outcome after climax."},
        {t:"Rising Action", d:"Events building toward climax."},
        {t:"Falling Action", d:"Events after climax leading to resolution."},
        {t:"Exposition", d:"Background information establishing setting/characters."},
        {t:"Inciting Incident", d:"Event that sets the main conflict in motion."},
        {t:"Epiphany", d:"Moment of sudden realization or insight."},
        {t:"Imagery", d:"Vivid description appealing to senses."},
        {t:"Figurative Language", d:"Non-literal language (metaphor, simile, personification)."},
        {t:"Connotation", d:"Implied meaning beyond literal definition."},
        {t:"Denotation", d:"Literal, dictionary definition."},
        {t:"Diction", d:"Author's choice of words and style."},
        {t:"Syntax", d:"Arrangement of words in sentences."},
        {t:"Colloquialism", d:"Informal language specific to region/group."},
        {t:"Jargon", d:"Specialized vocabulary of a profession/field."},
        {t:"Euphemism", d:"Mild expression replacing harsh/offensive term."},
        {t:"Malapropism", d:"Humorous misuse of similar-sounding words."},
        {t:"Spoonerism", d:"Switching initial sounds of words."},
        {t:"Anaphora", d:"Repetition of word/phrase at beginning of clauses."},
        {t:"Epistrophe", d:"Repetition of word/phrase at end of clauses."},
        {t:"Chiasmus", d:"Reversal of grammatical structure in parallel clauses."},
        {t:"Zeugma", d:"Word applies to multiple parts of sentence differently."},
        {t:"Synecdoche", d:"Part represents whole (e.g., 'wheels' for car)."},
        {t:"Metonymy", d:"Thing closely associated represents something else."},
        {t:"Paradox", d:"Statement that seems contradictory but may be true."},
        {t:"Pun", d:"Play on words with multiple meanings."},
        {t:"Satire", d:"Use of humor/irony to criticize."},
        {t:"Parody", d:"Imitation of style for comic effect."},
        {t:"Stream of Consciousness", d:"Writing that mimics flow of thoughts."},
        {t:"Free Verse", d:"Poetry without regular rhyme/rhythm."},
        {t:"Blank Verse", d:"Unrhymed iambic pentameter."},
        {t:"Sonnet", d:"14-line poem, usually iambic pentameter."},
        {t:"Haiku", d:"3-line Japanese poem (5-7-5 syllables)."},
        {t:"Ode", d:"Poem expressing exalted emotion."},
        {t:"Elegy", d:"Poem mourning death or loss."},
        {t:"Ballad", d:"Narrative poem meant to be sung."},
        {t:"Epic", d:"Long narrative poem about heroic deeds."},
        {t:"Villanelle", d:"19-line poem with complex rhyme scheme."},
        {t:"Sestina", d:"39-line poem with repeating end words."},
        {t:"Persuasive Essay", d:"Argues for or against a position."},
        {t:"Expository Essay", d:"Explains or informs about a topic."},
        {t:"Narrative Essay", d:"Tells a story with a point."},
        {t:"Descriptive Essay", d:"Paints picture with words."},
        {t:"Compare/Contrast", d:"Shows similarities and differences."},
        {t:"Cause/Effect", d:"Explains why things happen and results."},
        {t:"Problem/Solution", d:"Identifies problem and proposes solution."},
        {t:"Definition Essay", d:"Explains meaning of a concept."},
        {t:"Process Essay", d:"Explains how to do something."},
        {t:"Research Paper", d:"Presents findings from investigation."},
        {t:"Annotated Bibliography", d:"List of sources with summaries/evaluations."},
        {t:"Peer Review", d:"Process of evaluating others' work."},
        {t:"Revision", d:"Rewriting and restructuring content."},
        {t:"Editing", d:"Correcting grammar, punctuation, style."},
        {t:"Proofreading", d:"Final check for errors."},
        {t:"Plagiarism", d:"Using others' work/ideas without credit."},
        {t:"Citation", d:"Properly crediting sources (MLA, APA, Chicago)."},
        {t:"Works Cited", d:"List of all sources used."},
        {t:"Bibliography", d:"List of sources consulted."},
        {t:"Abstract", d:"Summary of research paper's main points."},
        {t:"Introduction", d:"Opening section that engages and informs."},
        {t:"Body Paragraphs", d:"Main content supporting thesis."},
        {t:"Conclusion", d:"Final section that summarizes and reflects."},
        {t:"Counterclaim Paragraph", d:"Acknowledges and refutes opposing views."}
    ],
    // --- HISTORY ---
    history: [
        {t:"Hammurabi's Code", d:"First written laws (Babylon). 'Eye for an eye'."},
        {t:"Magna Carta (1215)", d:"Limited King's power. Established Rule of Law."},
        {t:"Reformation (1517)", d:"Martin Luther's 95 Theses. Split from Catholic Church."},
        {t:"Renaissance", d:"Rebirth of art, science, philosophy (Da Vinci, Michelangelo)."},
        {t:"Columbian Exch.", d:"Transfer of goods/diseases between Old/New Worlds (1492+)."},
        {t:"Enlightenment", d:"Reason, individualism, skepticism of authority (Locke, Voltaire)."},
        {t:"American Rev (1776)", d:"Declaration of Independence. Rejection of British rule."},
        {t:"French Rev (1789)", d:"'Liberty, Equality, Fraternity'. Rise of Napoleon."},
        {t:"Industrial Rev", d:"Shift to machine manufacturing, steam power, urbanization."},
        {t:"WWI (1914-1918)", d:"Allied vs Central. Archduke Ferdinand assassination. Trench warfare."},
        {t:"Treaty of Versailles", d:"Ended WWI. Punished Germany, leading to WWII resentment."},
        {t:"WWII (1939-1945)", d:"Axis vs Allies. Holocaust. Nuclear warfare (Hiroshima/Nagasaki)."},
        {t:"Cold War", d:"Geopolitical tension between USA (Capitalism) and USSR (Communism)."},
        {t:"Civil Rights (1964)", d:"US Act outlawing discrimination. MLK 'I Have a Dream'."},
        {t:"Berlin Wall Fall", d:"1989. Symbolized the end of the Cold War and Soviet Union."},
        {t:"Apartheid End", d:"1994. Nelson Mandela elected President of South Africa."}
    ],
    // --- COMPUTER SCIENCE ---
    cs: [
        {t:"Binary", d:"Base-2 numeral system (0s and 1s). The language of computers."},
        {t:"Hexadecimal", d:"Base-16 system (0-9, A-F) used for colors/memory addresses."},
        {t:"Big O Notation", d:"Describes algorithmic complexity (Time/Space)."},
        {t:"O(1)", d:"Constant Time. Fastest. Array access."},
        {t:"O(log n)", d:"Logarithmic Time. Dividing dataset (Binary Search)."},
        {t:"O(n)", d:"Linear Time. Looping through all elements."},
        {t:"O(n²)", d:"Quadratic Time. Nested loops (Bubble Sort)."},
        {t:"Recursion", d:"A function that calls itself until a base case is met."},
        {t:"Stack", d:"LIFO (Last In, First Out) structure. (e.g., Undo, Call Stack)."},
        {t:"Queue", d:"FIFO (First In, First Out) structure. (e.g., Printer queue)."},
        {t:"Linked List", d:"Sequence of nodes with pointers to the next node."},
        {t:"Hash Table", d:"Key-value pairs. O(1) avg lookup. Uses hashing function."},
        {t:"Tree", d:"Hierarchical data structure. Root, Branches, Leaves."},
        {t:"Graph", d:"Collection of Nodes (items) and Edges (connections)."},
        {t:"Algorithm", d:"Step-by-step procedure for calculations/processing."},
        {t:"OOP", d:"Object-Oriented Programming (Classes, Objects, Inheritance)."},
        {t:"Encapsulation", d:"Restricting access to some object components (Private/Public)."},
        {t:"Polymorphism", d:"Treating objects of different classes appropriately."},
        {t:"API", d:"Application Programming Interface (Application glue)."},
        {t:"HTTP", d:"Hypertext Transfer Protocol. Standard of the Web."},
        {t:"REST", d:"Representational State Transfer. Architectural style for APIs."},
        {t:"DNS", d:"Domain Name System. Translates 'google.com' to IP address."},
        {t:"Encryption", d:"Encoding info so only authorized parties can access it."},
        {t:"Boolean Logic", d:"True/False. AND (&&), OR (||), NOT (!)."},
        {t:"TCP/IP", d:"Transmission Control Protocol/Internet Protocol (Internet backbone)."},
        {t:"OSI Model", d:"7 Layers: Physical, Data Link, Network, Transport, Session, Presentation, Application."},
        {t:"HTTP 200", d:"OK. Request succeeded."},
        {t:"HTTP 404", d:"Not Found. Resource doesn't exist."},
        {t:"HTTP 500", d:"Internal Server Error."},
        {t:"SQL", d:"Structured Query Language. SELECT * FROM table WHERE condition."},
        {t:"ACID", d:"Atomicity, Consistency, Isolation, Durability (Database transactions)."},
        {t:"Git", d:"Version Control System. commit, push, pull, branch, merge."},
        {t:"REST Verbs", d:"GET (read), POST (create), PUT (update), DELETE (remove)."},
        {t:"API Key", d:"Secret token for authentication with an API."},
        {t:"JSON", d:"JavaScript Object Notation. Lightweight data-interchange format."},
        {t:"XML", d:"Extensible Markup Language. Tag-based data format."},
        {t:"Compiler", d:"Translates source code (high-level) to machine code (low-level)."},
        {t:"Interpreter", d:"Executes instructions directly without compiling (e.g., Python, JS)."},
        {t:"Design Pattern", d:"Reusable solution to a commonly occurring problem (e.g. Singleton)."},
        {t:"NoSQL", d:"Non-relational database (MongoDB, Cassandra). Flexible schemas."},
        {t:"CAP Theorem", d:"Consistency, Availability, Partition tolerance. Pick two."},
        {t:"Machine Learning", d:"Systems that learn from data. Supervised vs Unsupervised."},
        {t:"Neural Network", d:"Computing system inspired by biological neural networks."},
        {t:"Blockchain", d:"Decentralized, distributed ledger technology."},
        {t:"Full Stack", d:"Development involving both Frontend (Client) and Backend (Server)."}
    ],
    reality: [
        "We are a way for the universe to know itself.",
        "You have survived 100% of your bad days.",
        "The atoms in your body were forged in stars.",
        "Time is relative; your now is unique.",
        "You are the universe experiencing itself.",
        "Everything you see is delayed by nanoseconds.",
        "You are spinning at 1,000 mph right now.",
        "Starlight is a ghost of the past.",
        "Your brain named itself.",
        "We are more bacteria than human by cell count."
    ],
    structure: {
        study: {
            sidebar: [
                { id: 'subjects', icon: 'book', label: 'Notebooks' },
                { id: 'flashcards', icon: 'layer-group', label: 'Flashcards' },
                { id: 'focus', icon: 'stopwatch', label: 'Deep Focus' },
                { id: 'tasks', icon: 'check-square', label: 'Task List' },
                { id: 'void', icon: 'trash-alt', label: 'The Void' }
            ]
        },
        utilities: {
            sidebar: [
                { id: 'breath', icon: 'lungs', label: 'Breathing' },
                { id: 'stopwatch', icon: 'clock', label: 'Stopwatch' },
                { id: 'calc', icon: 'calculator', label: 'Calculator' },
                { id: 'converter', icon: 'exchange-alt', label: 'Converter' },
                { id: 'dictionary', icon: 'book', label: 'Dictionary' },
                { id: 'formulas', icon: 'square-root-alt', label: 'Formulas' },
                { id: 'science', icon: 'flask', label: 'Science' },
                { id: 'ela', icon: 'pen-nib', label: 'ELA' },
                { id: 'history', icon: 'landmark', label: 'History' },
                { id: 'cs', icon: 'laptop-code', label: 'Comp Sci' }
            ]
        },
        sound: {
            sidebar: [
                { id: 'mixer', icon: 'sliders-h', label: 'Soundscapes' },
                { id: 'playlist', icon: 'broadcast-tower', label: 'Radio & Music' }
            ]
        },
        other: {
            sidebar: [
                { id: 'reality', icon: 'globe', label: 'Reality Check' },
                { id: 'settings', icon: 'cog', label: 'Settings' }
            ]
        }
    },

    // --- SOUND LIBRARY ---
    soundLibrary: {
        nature: [
            { id: 'rain', label: 'Rain', icon: 'cloud-rain' },
            { id: 'ocean', label: 'Waves', icon: 'water' },
            { id: 'stream', label: 'Stream', icon: 'tint' },
            { id: 'forest', label: 'Forest', icon: 'tree' }
        ],
        city: [
            { id: 'coffee', label: 'Cafe', icon: 'coffee' },
            { id: 'train', label: 'Train', icon: 'subway' },
            { id: 'city', label: 'City Traffic', icon: 'city' },
            { id: 'typing', label: 'Typing', icon: 'keyboard' }
        ],
        atmosphere: [
            { id: 'fire', label: 'Fireplace', icon: 'fire' },
            { id: 'night', label: 'Crickets', icon: 'moon' },
            { id: 'fan', label: 'Fan', icon: 'fan' },
            { id: 'vinyl', label: 'Vinyl', icon: 'record-vinyl' },
            { id: 'zen', label: 'Zen Bell', icon: 'bell' },
            { id: 'white', label: 'White Noise', icon: 'wave-square' }
        ]
    },

    radioStations: [
        { name: 'Lofi Girl - chill / study', url: 'https://www.youtube.com/embed/jfKfPfyJRdk' },
        { name: 'Chillhop - jazzy / lofi', url: 'https://www.youtube.com/embed/5yx6BWlEVcY' },
        { name: 'Coffee Shop - jazz / rain', url: 'https://www.youtube.com/embed/-5KAN9_CzSA' },
        { name: 'Synthwave - neon / drive', url: 'https://www.youtube.com/embed/4xDzrJKXOOY' },
        { name: 'Classical - piano / dark', url: 'https://www.youtube.com/embed/mCDSJ5McqVw' },
        { name: 'Ambient - space / sleep', url: 'https://www.youtube.com/embed/tNkZsRW7h2c' }
    ]
};